# Generated by Django 4.1 on 2022-09-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='available_stores',
            field=models.ManyToManyField(blank=True, null=True, to='account.offersstore'),
        ),
        migrations.DeleteModel(
            name='OfferAvailability',
        ),
    ]
